# Generated by Django 5.0.6 on 2024-05-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='info',
            name='phone',
            field=models.IntegerField(default=None),
        ),
    ]
