# Generated by Django 5.0.6 on 2024-05-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_app', '0002_info_email_info_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
