# Generated by Django 5.0.6 on 2024-05-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_app', '0003_alter_info_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.EmailField(default='jinal@gmail.com', max_length=254),
        ),
    ]
