# Generated by Django 5.0.6 on 2024-05-27 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_app', '0005_remove_info_email_info_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='city',
        ),
        migrations.RemoveField(
            model_name='info',
            name='phone',
        ),
    ]
