# Generated by Django 5.0.6 on 2024-05-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='image',
            new_name='receipe_image',
        ),
    ]
