# Generated by Django 5.0.6 on 2024-05-17 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_questions_choice_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='questions',
        ),
    ]
